markdown: kramdown

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", "vagrant", ".vagrant", "Vagrantfile"]
highlighter: pygments

permalink: /:title
baseurl: /robot-motion-planning-labs

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title: GCC Robotics Academy Robot Motion Planning Labs
tagline: Doing things the hard way

author:
  name: GCC Robotics Academy
  email: definitely.real@glendale.edu
  github: gcc-robotics/robot-motion-planning-labs

paginate: 1
